### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by horberlan** [CarlosMatheus/Tor-Chat-App#2]
can we make a graphical interface?

**Comment by CarlosMatheus** [comment]
Actually, it has a graphical interface when you open the chat client.

Check out this tutorial on how to start it:
https://www.youtube.com/watch?v=mcoticbMe_Q

I added it to the README now.

But if you mean to have a graphical interface to facilitate the whole process, even the initial setup to start both the server and the clients, I think it might be a good idea.

If you could elaborate more on what and how you think we could do it, we can discuss it.
